#!/bin/bash -e

# For this script we want a relative path to the directory
DIR="$(dirname $0)"

PROTO_PATH=$GOPATH/src:$GOPATH/src/github.com/gogo/protobuf/protobuf:$GOGOPROTO_ROOT:$DIR/client/update/v2
PROTO_PKGS="client/update/v2"

echo "Compiling protobuf files..."
for p in ${PROTO_PKGS}; do
    echo "Building ${p}..."
    protoc --proto_path=$PROTO_PATH --gofast_out=plugins=grpc:$DIR/client/update/v2 $DIR/${p}/*.proto
done
